modLoader="javafml"
loaderVersion="[36,)"
license="LGPL-v2.1"
updateJSONURL="https://tophat.cat/spruce-willis-the-xmas-tree/update.json"
issueTrackerURL="https://github.com/tophatcats-mods/spruce-willis-the-xmas-tree/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/spruce-willis-the-xmas-tree"
#logoFile=""
credits="ProxyNeko, Coda"
authors="ProxyNeko, Coda"

[[mods]]
modId="spruce-willis-the-xmas-tree"
version="${file.jarVersion}"
displayName="Spruce Willis the Xmas Tree"
description='''
Who doesn't love Spruce Willis!
'''

[[dependencies.creepy-creepers]]
   modId="forge"
   mandatory=true
   versionRange="[36,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.spruce-willis-the-xmas-tree]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16,)"
   ordering="NONE"
   side="BOTH"
